export function inferFileLanguage(path) {
  const name = String(path ?? '').trim().toLowerCase()
  if (!name) return 'plaintext'
  if (name.endsWith('.js') || name.endsWith('.cjs') || name.endsWith('.mjs') || name.endsWith('.jsx')) return 'javascript'
  if (name.endsWith('.ts') || name.endsWith('.tsx')) return 'typescript'
  if (name.endsWith('.vue')) return 'html'
  if (name.endsWith('.json')) return 'json'
  if (name.endsWith('.md')) return 'markdown'
  if (name.endsWith('.css')) return 'css'
  if (name.endsWith('.scss')) return 'scss'
  if (name.endsWith('.less')) return 'less'
  if (name.endsWith('.html') || name.endsWith('.htm')) return 'html'
  if (name.endsWith('.xml') || name.endsWith('.svg')) return 'xml'
  if (name.endsWith('.yml') || name.endsWith('.yaml')) return 'yaml'
  if (name.endsWith('.sh') || name.endsWith('.bash') || name.endsWith('.zsh')) return 'shell'
  if (name.endsWith('.ps1') || name.endsWith('.psm1') || name.endsWith('.psd1')) return 'powershell'
  if (name.endsWith('.py')) return 'python'
  if (name.endsWith('.sql')) return 'sql'
  if (name.endsWith('.ini') || name.endsWith('.cfg') || name.endsWith('.conf') || name.endsWith('.env')) return 'ini'
  if (name.endsWith('.dockerfile') || name.endsWith('/dockerfile') || name === 'dockerfile') return 'dockerfile'
  if (name.endsWith('.java')) return 'java'
  if (name.endsWith('.go')) return 'go'
  if (name.endsWith('.rs')) return 'rust'
  if (name.endsWith('.swift')) return 'swift'
  if (name.endsWith('.rb')) return 'ruby'
  if (name.endsWith('.php')) return 'php'
  if (name.endsWith('.c')) return 'c'
  if (name.endsWith('.h') || name.endsWith('.hpp') || name.endsWith('.hh') || name.endsWith('.hxx') || name.endsWith('.cpp') || name.endsWith('.cc') || name.endsWith('.cxx')) return 'cpp'
  return 'plaintext'
}
